# Based on work from Sonocotta


speaker:
  # Primary I2S speaker (PCM5100 DAC output)
  - platform: i2s_audio
    i2s_audio_id: i2s_output
    id: speaker_id
    dac_type: external
    i2s_dout_pin: ${i2s_dout_pin}
    channel: stereo
    sample_rate: 48000
    timeout: never

  # Mixer to combine announcement and media feeds
  - platform: mixer
    id: mixer_speaker_id
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
        timeout: never
      - id: media_spk_mixer_input
        timeout: never

  # Resampler for media playback
  - platform: resampler
    id: media_spk_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: media_spk_mixer_input

  # Resampler for announcements
  - platform: resampler
    id: announcement_spk_resampling_input
    task_stack_in_psram: ${task_stack_in_psram}
    output_speaker: announcement_spk_mixer_input